### ISSUE TITLE
Let's use official wheels

### ISSUE THREAD

**Issue by kmaehashi** [chainer-community/chainer-colab-notebook#14]
CuPy team now provides wheels on PyPI. I've updated procedures to use the latest official wheel, instead of ones in my repository.

https://github.com/kmaehashi/chainer-colab

This is not an urgent request, but please consider changing the installation steps to use official wheels.

**Comment by keisuke-umezawa** [comment]
Thanks for reporting issues! We will fix it.

**Comment by ikeyasu** [comment]
This issue is solved at #15 .
