### ISSUE TITLE
画像保存用

### ISSUE THREAD

**Issue by keisuke-umezawa** [chainer-community/chainer-colab-notebook#6]

**Comment by keisuke-umezawa** [comment]
<img width="1123" alt="2018-03-12 22 59 37" src="https://user-images.githubusercontent.com/1277089/37288041-9a8ae74e-2649-11e8-99ad-63d4d509e44a.png">
<img width="487" alt="2018-03-12 23 01 28" src="https://user-images.githubusercontent.com/1277089/37288044-9d7c53ca-2649-11e8-8b95-207f30347fe0.png">
<img width="847" alt="2018-03-12 23 02 57" src="https://user-images.githubusercontent.com/1277089/37288049-a0069bc8-2649-11e8-8937-0cd2d75da700.png">

**Comment by keisuke-umezawa** [comment]
<img width="470" alt="2018-03-12 23 00 35" src="https://user-images.githubusercontent.com/1277089/37288193-f8caf56a-2649-11e8-81ed-038e7736de75.png">

**Comment by keisuke-umezawa** [comment]
<img width="712" alt="2018-03-12 23 17 24" src="https://user-images.githubusercontent.com/1277089/37288870-a7d62f9c-264b-11e8-8334-ebf553c9fe30.png">
<img width="883" alt="2018-03-12 23 16 35" src="https://user-images.githubusercontent.com/1277089/37288857-a21b73fa-264b-11e8-9c70-0143e1c73439.png">

**Comment by ikeyasu** [comment]
![2018-03-21 15 18 45](https://user-images.githubusercontent.com/329257/37696602-3b5e93a0-2d1b-11e8-924f-96301daecb22.png)
