### ISSUE TITLE
CUDARuntimeError('cudaErrorUnknown: unknown error',)

### ISSUE THREAD

**Issue by kritdikoon** [chainer-community/chainer-colab-notebook#75]
I have run the first 2 scripts as below.

There is an error in CUDA Runtime Version:

CUDA Runtime Version  : CUDARuntimeError('cudaErrorUnknown: unknown error',)

How should I solve this issue?

=============================
Script
----------------------------------------------------
!curl https://colab.chainer.org/install | sh -

=============================
Result
----------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1379  100  1379    0     0   5868      0 --:--:-- --:--:-- --:--:--  5868
+ apt -y -q install cuda-libraries-dev-9-2
Reading package lists...
Building dependency tree...
Reading state information...
cuda-libraries-dev-9-2 is already the newest version (9.2.148-1).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
+ pip install -q cupy-cuda92  chainer 
+ set +ex
Installation succeeded!
====================================
Script
----------------------------------------------------
import chainer
import cupy
chainer.print_runtime_info()
print('GPU availability:', chainer.cuda.available)
print('cuDNN availablility:', chainer.cuda.cudnn_enabled)

======================================
Result 
----------------------------------------------------
Platform: Linux-4.14.65+-x86_64-with-Ubuntu-18.04-bionic
Chainer: 5.0.0
NumPy: 1.14.6
CuPy:
  CuPy Version          : 5.1.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 9020
  CUDA Driver Version   : 9020
  **CUDA Runtime Version  : CUDARuntimeError('cudaErrorUnknown: unknown error',)**
  cuDNN Build Version   : 7301
  cuDNN Version         : 7301
  NCCL Build Version    : 2307
iDeep: 2.0.0.post3
GPU availability: True
cuDNN availablility: True

**Comment by keisuke-umezawa** [comment]
@kritdikoon 
Thank you for the issue!
By the way, did you try these commands on your new notebook?
In that case, you should change the runtime from cpu to gpu.

I reproduced the same behavior when I ran these commands on a cpu instance.
![2018-12-27 14 31 03](https://user-images.githubusercontent.com/1277089/50467070-77495980-09e4-11e9-8f82-042cbda25d6c.png)

**Comment by kritdikoon** [comment]
keisuke-umezawa  san
Thank for your prompt reply.
Your answer solves the issue.

1) Menu Bar
Runtime  > Change runtime type 

2) Change Hardware accelerator to [ GPU ]  

3) [ SAVE ] 

INPUT ==============================
import chainer
import cupy
chainer.print_runtime_info()
print('GPU availability:', chainer.cuda.available)
print('cuDNN availablility:', chainer.cuda.cudnn_enabled)

OUTPUT ==============================
Platform: Linux-4.14.65+-x86_64-with-Ubuntu-18.04-bionic
Chainer: 5.0.0
NumPy: 1.14.6
CuPy:
  CuPy Version          : 5.0.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 9020
  CUDA Driver Version   : 9020
  CUDA Runtime Version  : 9020
  cuDNN Build Version   : 7201
  cuDNN Version         : 7201
  NCCL Build Version    : 2213
iDeep: 2.0.0.post3
GPU availability: True
cuDNN availablility: True

=============================

Many thanks again!
